version: '3'
services:
  development:
    build:
      context: .
      dockerfile: Dockerfile
    user:
      developer
    volumes:
      - .:/workspace:cached
    environment:
      - SDL_VIDEODRIVER=x11
      - DISPLAY=${DISPLAY}
      - TERM=xterm-256color
      - force_color_prompt=1
    ports:
      - "8888:8888"
    tty: true
